# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: BuildPublish
  displayName: Build and Publish images
  jobs:  
  - job: Build
    displayName: Build and Publish
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Docker HUB'
        repository: 'marosvalter/jukebox'
        command: 'buildAndPush'
        dockerfile: '$(Build.SourcesDirectory)/Jukebox/Dockerfile'
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Build an ARM image
      inputs:
        containerRegistry: 'Docker HUB'
        repository: 'marosvalter/jukebox'
        command: 'buildAndPush'
        dockerfile: '$(Build.SourcesDirectory)/Jukebox/Dockerfile.arm'
        tags: |
          $(tag)
          ARM